development:
  mail_chimp_api_key: "5f4bb7c596078d9d538075c5a3094abd-us8"
  mail_chimp_list_key: "6c61fd5daa"
  facebook_key: ""
  facebook_secret: ""
  site_url: "http://localhost:3000"
  
staging:
  mail_chimp_api_key: "5f4bb7c596078d9d538075c5a3094abd-us8"
  mail_chimp_list_key: "6c61fd5daa"
  facebook_key: " "
  facebook_secret: " "
  site_url: "http://staging-toddlerosity.herokuapp.com"
  
production:
  mail_chimp_api_key: "5f4bb7c596078d9d538075c5a3094abd-us8"
  mail_chimp_list_key: "6c61fd5daa"
  facebook_key: ""
  facebook_secret: ""
  site_url: "http://mycombate.com"